### ISSUE TITLE
Sony releases Headphones Connect 10.2.0

### ISSUE THREAD

**Issue by pupu2314** [eiarhabi/MDR_LEAUDIO#2]
Sony releases Headphones Connect 10.2.0
I wonder if the corresponding modified version will be released?
https://www.apkmirror.com/apk/sony-corporation/sony-headphones-connect/sony-headphones-connect-10-2-0-release/

**Comment by eiarhabi** [comment]
Maybe. But I don't think there's any significant functionality change for this version so I doubt it.

**Comment by Guille05** [comment]
The newest firmware releases by Sony require the most recent app, it would be helpful if you could update it as they still don't seem to be interested in allowing non-Sony devices to use LE audio.

**Comment by mmis1000** [comment]
It seems sony released new firmware of wf-1000xm5 . And the new firmware does not work with this modified sony connect app.(connect to updated headphones result in a prompt that ask you to update the app from google play) Probably a new mod from latest connect app is required now.
